### ISSUE TITLE
 iBus Cannot Connect to Elasticsearch Node

### ISSUE THREAD

**Issue by dawidaleksanderwalczak** [informationgrid/informationgrid.github.io#3]
**Description:**
I am trying to set up an InGrid node locally by manually installing the various components, dependencies, and modules for a minimal setup as descripted at https://www.ingrid-oss.eu/latest/system/installation.html:
- Elasticsearch
- iBus
- Portal
- iPlug IGE / InGrid Catalog
- Codelist Repository

1. I have installed the necessary dependency for Elasticsearch using the Docker container provided at https://docker-registry.wemove.com/ingrid-elasticsearch-with-decompound:6.4.2.
2. For the Elasticsearch cluster configuration, I have set up the following docker-compose.yml file: 
```yaml
version: '3'
services:
  elastic:
    image: docker-registry.wemove.com/ingrid-elasticsearch-with-decompound:6.4.2
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - TZ=Europe/Berlin
      - cluster.name=ingrid
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1024M
```
These settings were taken 1:1 from https://github.com/informationgrid/ingrid-docker/blob/main/docker-compose.yml and I added the following port mapping for safety:
```yaml
    ports:
      - "9200:9200"
      - "9300:9300"
```

3. I have confirmed that the Elasticsearch cluster is up and running. It is accessible at http://localhost:9200/ and shows the following information:
```json
{
  "name" : "tth8Nt0",
  "cluster_name" : "ingrid",
  "cluster_uuid" : "85PCb6KXT9-RZCyrU8rl9Q",
  "version" : {
    "number" : "6.4.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "04711c2",
    "build_date" : "2018-09-26T13:34:09.098244Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
4. The cluster is in a green state (http://localhost:9200/_cluster/health):
```json
{
  "cluster_name": "ingrid",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 0,
  "active_shards": 0,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```
5. I have successfully installed the iBus component on Windows (not within a Docker container) and it is accessible at http://localhost:9901.

**Problem:**
When navigating to http://localhost:9901/#/indices, I receive the following error:
![image](https://github.com/informationgrid/informationgrid.github.io/assets/61883941/f832383c-071a-4ab2-af5a-fb117f9b53ab)

In the iBus log file (log.log), I see the following errors:
```java
INFO [2024-06-10 08:39:06] (ConfigurationService.java:77) - Elasticsearch not connected ... Reconnecting
 INFO [2024-06-10 08:39:06] (PluginsService.java:205) - no modules loaded
 INFO [2024-06-10 08:39:06] (PluginsService.java:208) - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
 INFO [2024-06-10 08:39:06] (PluginsService.java:208) - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
 INFO [2024-06-10 08:39:06] (PluginsService.java:208) - loaded plugin [org.elasticsearch.reindex.ReindexPlugin]
 INFO [2024-06-10 08:39:06] (PluginsService.java:208) - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
 INFO [2024-06-10 08:39:06] (PluginsService.java:208) - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
 INFO [2024-06-10 08:39:06] (PluginsService.java:208) - loaded plugin [org.elasticsearch.xpack.core.XPackClientPlugin]
 WARN [2024-06-10 08:39:06] (IndicesService.java:111) - Could not connect to elasticsearch node
ERROR [2024-06-10 08:39:10] (RestResponseEntityExceptionHandler.java:45) - Exception occurred:
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{0ExqjCmhQjqwQTJNLKChKA}{localhost}{127.0.0.1:9300}]
```
**Additional Information:**
- I installed iBus manually on Windows because the Docker images did not work for me.
- I did not change the default settings of iBus.
- I installed ingrid-ibus-7.1.0-installer.jar.
- I have attached the log.log file for more details.

**Question:**
What am I doing wrong? How can I ensure that iBus communicates correctly with the Elasticsearch node?

**Attachments:**
- [log.log](https://github.com/user-attachments/files/15757479/log.log)
-  [application-default.properties](https://github.com/user-attachments/files/15757491/application-default.txt)
